### ISSUE TITLE
regional won't redirect http to https

### ISSUE THREAD

**Issue by Enalmada** [skriems/next-material#1]
I used this example to experiment with serverless and it worked great!  Thank you for taking the time to put it together.

Consider mentioning in the readme that regional endpoints for custom domains must be hit with https.  When I first set this up, hitting my custom domain in the browser failed and that had me scratching my head for a while.  Luckily I eventually tried https and it worked fine but not all new users will do that and will think the example doesn't work.   

You could mention that to get http -> https redirecting there are two options: disable serverless custom domains and setup a cloudfront distribution in front of your gateway api enabled with custom domain, or use "endpointType: edge" and AWS will manage cloudfront with custom domain for you. 

Potentially good resource to link to:
https://stackoverflow.com/questions/49826230/regional-edge-optimized-api-gateway-vs-regional-edge-optimized-custom-domain-nam

BTW, after playing around with this a bit, it seems much more appropriate to me for a next.js user to use regional setting with no custom domain.  Then they put their own cdn in front to cache next.js static resources and redirect to https.

**Comment by skriems** [comment]
I noticed as well that HTTP is unfortunately not redirected to HTTPS. I'm going to add that info and the link you provided, thanks for that @Enalmada!
Going to check the options with my personal site I'm running with the same setup currently.
